### ISSUE TITLE
Slash on S3 credentials causes problems

### ISSUE THREAD

**Issue by quiuquio** [mcolomer/any-file#1]
Hello,

this will fail if a S3 secret key has any "/" on it, which can happen quite often.
The problem seems to be in __parseUrl().

Perhaps checking for the length of username and password in the s3 case could help?
Thanks!

Regards,
Robert

**Comment by mcolomer** [comment]
Thanks quiuquio. I will check it and fix the issue detected.
Regards!

**Comment by mcolomer** [comment]
Hi @quiuquio,

Now you can use any credential containing / before @ (not only s3).
Hope this helps.

Regards and enjoy,
