### ISSUE TITLE
Unable to transfer files from aws s3 to aws ec2

### ISSUE THREAD

**Issue by Chayan-19** [mcolomer/any-file#10]
var anyfile = require("any-file");
const AnyFile = require("any-file/lib");
var af = new AnyFile();
var fromFile =
  "s3://secret_key_id:secret_access_key@s3.amazon.com/my-test-bucket/filename.zip";
var toFile =
  "sftp://username:password@ec2.amazon.com:public_IP/home/pathname/filename.zip";

try {
  af.from(fromFile).to(toFile, function (err, res) {
    console.log(res);
    process.exit();
  });
} catch (err) {
  console.log(err);
}

I used the same code to tranfer files from my local machine to aws s3 and vice versa and it worked completely fine.
But when I am trying to transfer files from aws s3 to aws ec2 I am getting a true response but the file is not present in the server. I verified it from filezilla. Could you please help me with this. I have also tried removing the colon after amazon.com, tried adding the public IP of my aws ec2 instance but nothing works. I'm getting a true response but the file is not showing up in the server.

**Comment by mcolomer** [comment]
Hi @Chayan-19 ,

I have tested and it seems that something is wrong with Access/Secret Keys values.
Basically, a / in those keys affects someway but not sure why.

I have changed a bit the code and tested a trasfer from a https file (located in s3 with public perms) to an sftp this way:

var fromFile = "https://BUCKET_NAME.s3.amazonaws.com/file.ext";
var toFile = "sftp://USER@HOST/file.ext"; //you have to be able to connect to HOST with USER without password.
try {
  anyfile.from(fromFile).to(toFile, function(err, res) {
    console.log(res);
    process.exit();
  });
} catch (err) {
  console.log(err);
}

Callback returns true.

So it seems something related with slash on S3 credentials but deep testing is required.

**Comment by Chayan-19** [comment]
Actually the servers I'll be transferring the data to will have a password and I can't tell them to remove the passwords.
Anyways thanks for your help

**Comment by mcolomer** [comment]
You can bypass this, adding an authorized public key.

If you want to connect to a server with a specific user (like it), a public key must be defined under 

`/home/it/.ssh/authorized_keys

You can generate your own key from origin server. Suppose that user there is it too.
Connected by ssh with that user, you need to do:

`ssh-keygen

This will generate a key pair under ~/.ssh

Just echo id_rsa.pub file and add the string to the authorized_keys file in destination server.
Adding this discards password promp when connecting to destination server.

Hope this helps.
