### ISSUE TITLE
S3 doesn't work with V4 signature, AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by madsoulswe** [mcolomer/any-file#3]
Eu-central-1 doesn't support v2.
Maybe add another parameter to the url or a querystring?

**Comment by mcolomer** [comment]
Thanks Dennis.

As you said, signatureVersion must be specified when calling S3 constructor.
Let me test it and I will publish the fix.

**Comment by mcolomer** [comment]
Updated project libraries to fix aws-sdk problems with eu-central-1 endpoints on s3.
Remove node_modules and launch npm install to install updated packages. 

Please, let me know if it works correctly with eu-central-1.

Anyway, your feedback is really welcome.
